sqlserver.url=jdbc:sqlserver://lavanya-dataproduct-sql.database.windows.net:1433;database=DataMigrationDB;encrypt=true;trustServerCertificate=false;loginTimeout=30;
sqlserver.username=sqladmin
<<<<<<< HEAD
sqlserver.password=YOUR_PASSWORD
=======
sqlserver.password=DataMigration@2026

azure.storage.connection-string=###
azure.storage.container-name=migration-files
azure.storage.file-system=migration-files
>>>>>>> 573c3db (Implemented AzureStorageUploader and connected to azure data lake storage)
