sqlserver.url=jdbc:sqlserver://lavanya-dataproduct-sql.database.windows.net:1433;database=DataMigrationDB;encrypt=true;trustServerCertificate=false;loginTimeout=30;
sqlserver.username=sqladmin
sqlserver.password=YOUR_PASSWORD
